package Part2.Exception;

public class Task1 {
    public static void main(String[] args) {

    }
    public static int
}
